apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd

spec:
  project: default

  sources:
    repoUrl: https://github.com/CityBandit/Argocd.git # key in the repo url
    targetRevision: HEAD
    path: /k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp # The namespace of your application

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false # allow deleting of all application resources during automatic syncing ( false by default ).
